server:
  port: 9999

spring:
  datasource:
     url: jdbc:mysql://localhost:3306/sys-user?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: sqlhero
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



