management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
# remote git
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/herosql/Springcloud_config
          searchPaths: /shared
          username: herosql
          password: qwer@1234
      label: master
      force-pull: true
  application:
      name: config-server
  rabbitmq:
        host: 192.168.3.163
        port: 5672
        username: rabbitadmin
        password: 123456
        publisher-confirms: true
        virtual-host: /

server:
  port: 8769